version: '3'

services:
  postgres:
    image: postgres:13
    container_name: sb_database
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./var:/docker-entrypoint-initdb.d/

  registry:
    image: registry:2.8.3
    env_file:
      - .env
    ports:
      - "${DOCKER_REGISTRY_PORT}:5000"
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    volumes:
      - registry_data:/var/lib/registry
volumes:
  postgres_data:
  registry_data:
